# Generated by Django 5.2.7 on 2025-10-22 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_category_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='alt_image',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='posts', to='blogs.tag'),
        ),
        migrations.AlterField(
            model_name='section',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='section'),
        ),
    ]
